FE-807
WeatherXM/docs pull request #103
Opened 2024-05-17 08:27 UTC by ipanagiv

2024-05-18 07:38 UTC, PavlosTze requested changes
Also please fix the spellcheck issue.

2024-05-18 07:38 UTC, PavlosTze commented on docs/wxm-devices/wifi-m5-bundle/m5-assemble.mdx
> +sidebar_label: Assembling Assembling WS1000
Assembling is twice

2024-05-20 08:54 UTC, PavlosTze requested changes

2024-05-20 10:39 UTC, ipanagiv commented on docs/wxm-devices/wifi-m5-bundle/m5-assemble.mdx
> +sidebar_label: Assembling Assembling WS1000
thanks!

2024-05-20 10:49 UTC, PavlosTze approved these changes

2024-05-20 11:07 UTC, merged