WB3000 public documentation
WeatherXM/docs pull request #129
Opened 2024-07-22 14:16 UTC by ipanagiv

Resolves FE-343, FE-348, FE-346, FE-990, FE-344, FE-345, FE-347, FE-1037, FE-1038, FE-1036

2024-07-23 10:09 UTC, gkoumanos requested changes
Please review my comments

2024-07-23 10:09 UTC, gkoumanos commented on docs/wxm-devices/Pulse-bundle/Pulse-troubleshooting.mdx
> +Assuming that the WG3000 Gateway unit is placed outdoors facing south, this may be due to a bad RF connection between the Pulse Gateway and the outdoor station.
`Pulse Gateway` multiple names for the same thing causes confusion

2024-07-23 10:09 UTC, gkoumanos commented on docs/wxm-devices/Pulse-bundle/pulse-bundle-introduction.mdx
> +Powered via a small solar panel and batteries and communicates with the WG1200 Gateway via RF (Radio Frequencies).
WG1200

2024-07-23 10:09 UTC, gkoumanos commented on docs/wxm-devices/Pulse-bundle/pulse-bundle-introduction.mdx
> +The maximum distance between this station and the WG1200 is 100m with line of sight.
WG1200

2024-07-23 10:09 UTC, gkoumanos commented on docs/wxm-devices/Pulse-bundle/pulse-bundle-introduction.mdx
> +- #### Temperature:
I skipped the specs. I assume they are right

2024-07-23 10:09 UTC, gkoumanos commented on docs/wxm-devices/Pulse-bundle/pulse-bundle-introduction.mdx
> +  - Reporting Interval: 16 seconds
Not 16. Most probably 20.

2024-07-23 10:09 UTC, gkoumanos commented on docs/wxm-devices/Pulse-bundle/pulse-contents.mdx
> +The Pulse Gateway is advised to be placed outdoors, ideally on a the same pole as the Weather Station, to ensure the best possible connection to the cellular network and with the Weather Station.
Name

2024-07-23 10:09 UTC, gkoumanos commented on static/img/wxm-devices/pulse-bundle/pulse-location.jpeg
Why not Manhattan map? Also greek text???

2024-07-23 11:01 UTC, ipanagiv commented on docs/wxm-devices/Pulse-bundle/Pulse-connect-and-claim.mdx
> +- Model C: 921 MHz
The pulse has the frequency available. With whom should we confirm?

2024-07-23 11:02 UTC, gkoumanos commented on docs/wxm-devices/Pulse-bundle/Pulse-connect-and-claim.mdx
> +- Model C: 921 MHz
@NikosTsiligaridis do we have WS1001 in 921 too? Doubt it...

2024-07-23 11:19 UTC, ipanagiv commented on docs/wxm-devices/Pulse-bundle/pulse-bundle-introduction.mdx
> +The maximum distance between this station and the WG1200 is 100m with line of sight.
thanks!

2024-07-23 11:28 UTC, ipanagiv commented on static/img/wxm-devices/pulse-bundle/pulse-location.jpeg
done thanks

2024-07-23 11:30 UTC, ipanagiv commented on docs/home.mdx
> +        <p>The WB3000 is a bundle product, that combines the WS1001 weather station with our PULSE 4G - LTE gateway (WB3000). </p>
i got it from the shop: https://weatherxm.com/product/wb3000-4g/

2024-07-23 12:38 UTC, gkoumanos commented on docs/wxm-devices/Pulse-bundle/pulse-bundle-introduction.mdx
> +  - Reporting Interval: 16 seconds
30

2024-07-23 13:06 UTC, gkoumanos commented on docs/home.mdx
> +        <p>The WB3000 is a bundle product, that combines the WS1001 weather station with our PULSE 4G - LTE gateway (WB3000). </p>
@ipanagiv  model in parenthesis is WG... not WB...

2024-07-23 20:43 UTC, PavlosTze approved these changes

2024-07-24 07:18 UTC, PavlosTze approved these changes

2024-07-24 07:20 UTC, gkoumanos commented on docs/wxm-devices/pulse-bundle/introduction.mdx
> +Powered via a small solar panel and batteries and communicates with the WG3000 Gateway via RF (Radio Frequencies).
Called just WG3000 in the other tab

2024-07-24 07:20 UTC, gkoumanos commented on docs/wxm-devices/pulse-bundle/connect-and-claim.mdx
> +    Navigate to "Devise Settings" menu by pressing the arrow keys on your WG3000 right on the screen and select the "Claim Device" option, a QR code will appear.
typo: Devise. Please copy paste all docs in spellchecker

2024-07-24 07:20 UTC, gkoumanos commented on docs/wxm-devices/pulse-bundle/maintenance.mdx
> +      <li>Clean the rain gauge at least once every 3 months.</li>
Numbered list does not correspond to the number on the graphic. Is this reused somehow for D1 too? If not replicate change there too

2024-07-24 07:26 UTC, PavlosTze commented on docs/wxm-devices/pulse-bundle/pulse-contents.mdx
> +      <li>Power supply cable (USB-C)</li>
Yes, we do the same on [M5 ](https://docs.weatherxm.com/wxm-devices/wifi-m5-bundle/m5-contents) and [D1](https://docs.weatherxm.com/wxm-devices/D1-bundle/D1-contents).

2024-07-24 07:37 UTC, PavlosTze commented on static/img/wxm-devices/pulse-bundle/contents-included-pulse.png
Let's move on without that in order not to lose time, as it's minor, and I informed the designer to look into it and give us a new sketch whenever they can. But, good catch :)

2024-07-24 07:51 UTC, PavlosTze commented on static/img/wxm-devices/pulse-bundle/contents-included-pulse.png
Nevermind, fixed it we got the new icon :)

2024-07-25 07:29 UTC, gkoumanos approved these changes
LGTM

2024-07-25 09:42 UTC, merged