[BE-256]: update rmv2
WeatherXM/docs pull request #49
Opened 2023-11-02 15:46 UTC by tmavroeid

2023-11-03 12:27 UTC, PavlosTze requested changes
Some very minor changes @tmavroeid and we are good to go.

2023-11-03 12:27 UTC, PavlosTze commented on docs/project/reward-mechanism-v2.mdx
> +  \
What are these used for @tmavroeid ? I think these `\` on that list are unnecessary.

2023-11-03 12:27 UTC, PavlosTze commented on docs/project/reward-mechanism-v2.mdx
> +To read more please see our [whitepaper](https://weatherxm.com/whitepaper)
A dot is missing at the end.

2023-11-08 08:35 UTC, NikosTsiligaridis approved these changes
Gj @tmavroeid. 
I will be adding more details on QoD, PoL, CC, etc and consolidate the RM1 + RM1.5 + RM2 into a single doc soon, to help clarify our current status and future direction, so I will move stuff around in this article.

2023-11-08 08:37 UTC, NikosTsiligaridis commented on docs/project/reward-mechanism-v2.mdx
> +To read more please see our [whitepaper](https://weatherxm.com/whitepaper)
ninja vision.

2023-11-08 08:38 UTC, merged