FE-640 Reward-boosts
WeatherXM/docs pull request #80
Opened 2024-03-04 18:56 UTC by ipanagiv

2024-03-04 21:24 UTC, PavlosTze requested changes

2024-03-04 21:24 UTC, PavlosTze commented on sidebars.js
> +				  "rewards/reward-boosts"
Let's move this new boosts secton above "Rewards Claiming" please.

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +title: Rewards Boosts
Rewards -> Reward

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +sidebar_label: Rewards Boosts
Rewards -> Reward

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +slug: /project/rewards-boosts
rewards-boosts -> reward-boosts

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +In addition to the **Base Rewards**, a device already gets for contributing to weather data during the regular daily distribution. Learn more about the daily rewards [Reward Mechanism (RM) ](/reward-
I think a sentence is missing here before "In addition" e.g. "Reward boosts are rewards......"

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +So far the following **Reward Boosts** are implemented:
Hmmm not true, Beta Rewards is almost implemented, but Cell Boost is **not**, it's just the next boost down in the pipeline. So let's not say "implemented" here as it's a wrong term.

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +According to the [Token Allocation table](https://weatherxm.network/docs/wxm-token.html#token-allocation) 3M $WXM are reserved to reward stations that participated to the network before the Token Lau
a comma is needed before the "3M $WXM"

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +Calculation:
Calculation --> #### Calculation

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +This is the percentage of the 3m tokens that correspond to the rewardable hours the station provided.
3m --> 3M

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +`RewardableBetaHours[s]`.
Instead of a dot at the end please use `:`

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +`StationBetaRewards[s] = 3000000 * RewardableBetaHours[s]/Sum(RewardableBetaHours of all stations)`
Add at the end please a `:`

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +This is the beta rewards allocated daily to this station.
Please move those in a new line and do the following:

`DailyBetaRewards[s] = StationBetaRewards[s]/365`: This is the beta rewards allocated daily to this station.

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +Stations must have a wallet defined to be part of the Beta Rewards allocation.
Let's rephrase it to:

> Each user who has a station eligible for beta rewards, must have a wallet defined to be part of the Beta Rewards allocation.

And hyperlink the "wallet" to the "Add/edit wallet address" section in our docs please.

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +- As part of the &&Beta Rewards** program, the first 100 devices that join the network will receive tokens.
&&Beta Rewards** --> **Beta Rewards**

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +#### Examples of reward programs that may be implemented using **Rewards Boost**, in the near future are:
Let's rephrase it to:

> Examples of reward boosts that may be implemented in the near future are:

And instead of `####` use `###`

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +The **Rewards Boost** is a mechanism that can be used to incentivize specific behavior from devices. It is a flexible mechanism that can be used to incentivize any behavior that is beneficial to the
Rewards Boost -> Reward Boosts

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +All the above are **examples** of reward programs that may be implemented using the Rewards Boost mechanism.
Let's rephrase it to:

> All the above are **examples** of reward boosts that may be implemented.

2024-03-04 21:24 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +## Overview
Let's use `###` please for better structure below.

2024-03-05 18:01 UTC, PavlosTze approved these changes

2024-03-12 07:48 UTC, eeVoskos requested changes

2024-03-12 07:48 UTC, eeVoskos commented on docs/rewards/reward-boosts.mdx
> +According to the [Token Allocation table](https://weatherxm.network/docs/wxm-token.html#token-allocation), 3M $WXM are reserved to reward stations that participated to the network before the Token La
```suggestion
According to the [Token Allocation table](https://weatherxm.network/docs/wxm-token.html#token-allocation), 3M $WXM are reserved to reward stations that participated to the network before the Mainnet Launch Day ("Beta period").
```

2024-03-12 07:48 UTC, eeVoskos commented on docs/rewards/reward-boosts.mdx
> +The following calculations will take place for each station, the day before the Token Launch:
```suggestion
The following calculations will take place for each station, the day before the Mainnet Launch:
```

2024-03-12 07:48 UTC, eeVoskos commented on docs/rewards/reward-boosts.mdx
> +`StationBetaRewards[s] = 3000000 * RewardableBetaHours[s]/Sum(RewardableBetaHours of all stations)`:
This syntax is somewhat confusing. I strongly suggest we go with Math formula syntax, as described here:
https://github.blog/2022-05-19-math-support-in-markdown/

The content could be take - and adapted - from here our internal outline wiki.

2024-03-12 07:48 UTC, eeVoskos commented on docs/rewards/reward-boosts.mdx
> +Cell Boost is a mechanism that can be used to incentivize waether stations to be deployed on a specific cell.
```suggestion
Cell Boost is a mechanism that can be used to incentivize weather station deployments on a specific cells / areas of interest.
```

2024-03-12 07:48 UTC, eeVoskos commented on docs/rewards/reward-boosts.mdx
> +- As part of the **Beta Rewards** program, the first 100 devices that join the network will receive tokens.
This is just an idea, not to be publicly communicated.
```suggestion
```

2024-03-12 07:48 UTC, eeVoskos commented on docs/rewards/reward-boosts.mdx
> +- Devices that contribute to the network during a specific event, such as a natural disaster, will receive a boost in rewards.
```suggestion
- Devices that contribute to the network during a specific event, such as a natural disaster, may receive a boost in rewards.
```

2024-03-12 07:48 UTC, eeVoskos commented on docs/rewards/reward-boosts.mdx
> +- Demand driven rewards, a third party who needs data from specific cells.
This is the cell boost.
```suggestion
```

2024-03-12 10:05 UTC, ipanagiv commented on docs/rewards/reward-boosts.mdx
> +**Reward boosts** are additional rewards given to devices that contribute weather data during daily distribution, added to their **base rewards**. Learn more about the daily rewards at the [Reward Me
added.

2024-03-14 10:37 UTC, PavlosTze requested changes

2024-03-14 10:37 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +**Reward boosts** are additional rewards given to stations that contribute weather data during daily distribution,in addition to the [**base rewards**](/reward-mechanism#daily-rewards-calculation-pro
daily distribution,in addition to the -----> daily distribution, in addition to the

2024-03-14 10:37 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +**Reward Boosts** rewards stations with extra $WXM tokens for meeting specific criteria.
rewards stations ---> reward stations

2024-03-14 18:39 UTC, PavlosTze commented on docs/rewards/reward-boosts.mdx
> +**Reward Boosts** rewards stations with extra $WXM tokens for meeting specific criteria.
Fix this also @ipanagiv please!

2024-03-14 19:44 UTC, PavlosTze approved these changes

2024-03-14 20:03 UTC, eeVoskos approved these changes

2024-03-14 21:28 UTC, merged