Fe 534
WeatherXM/docs pull request #84
Opened 2024-03-26 17:21 UTC by ipanagiv

2024-03-27 09:41 UTC, PavlosTze requested changes
Good job @ipanagiv , some minor changes needed which are mentioned below. Also, consider changing these ones also:
1. https://docs.weatherxm.com/faqs#can-i-change-my-wallet-address-in-the-future (testnet mention)
2. https://docs.weatherxm.com/project/rewards-troubleshooting (the two notes regarding the "PoL penalization while on testnet").

2024-03-27 09:41 UTC, PavlosTze commented on docs/wallet/add-edit-wallet-address.mdx
>  While we are on the testnet, we suggest you use a **MetaMask** wallet with WeatherXM. By following our guide, it's
This is wrong. Replace this. We need to write something that will say that we have tested Metamask etc. and in the future we will add a paragraph showing the supported wallets.

2024-03-27 09:41 UTC, PavlosTze commented on docs/wallet/add-edit-wallet-address.mdx
> +If you want to confirm the existence of your tokens in your preferred wallet, you need to add our ERC20 token's smart contract.See how [here](https://docs.weatherxm.com/wallet/how-to-join-arbitrum-an
Leave a space at the dot at "smart contract.See how "

2024-03-27 09:41 UTC, PavlosTze commented on docs/the-$WXM-token.mdx
> +WeatherXM is deployed at Arbitrum One Network. You can find the contract at [Arbitrum One Explorer](https://arbiscan.io/token/0xb6093b61544572ab42a0e43af08abafd41bf25a6)
deployed at ---> deployed on

2024-03-27 09:41 UTC, PavlosTze commented on docs/rewards/rewards-claiming.mdx
> + However, once on Arbitrum you can enjoy lower gas fees. Once the amount is correct, click “Confirm”
Please add a dot at the end.

2024-03-27 09:41 UTC, PavlosTze commented on docs/rewards/rewards-claiming.mdx
> + **This Guide is only on desktop with the MetaMask browser extension already installed.**
This guide is only on ----> This guide is applicable only for

2024-03-27 13:03 UTC, PavlosTze requested changes
1. https://docs.weatherxm.com/faqs#can-i-change-my-wallet-address-in-the-future (testnet mention)
2. https://docs.weatherxm.com/project/rewards-troubleshooting (the two notes regarding the "PoL penalization while on testnet").

2024-03-27 13:03 UTC, PavlosTze commented on docs/wallet/add-edit-wallet-address.mdx
> +#WXM is deployed on Arbitrum One Network. We suggest you use a **MetaMask** wallet with WeatherXM, as we have extensivelly tested on it. As we evolve, we will official support several wallets.
#WXM -> $WXM

2024-03-27 20:45 UTC, PavlosTze requested changes
Please handle this @ipanagiv https://docs.weatherxm.com/faqs#can-i-change-my-wallet-address-in-the-future (testnet mention)

2024-03-28 16:21 UTC, PavlosTze approved these changes

2024-05-21 20:06 UTC, PavlosTze approved these changes

2024-05-24 14:57 UTC, PavlosTze requested changes
@ipanagiv Remove the images you do not use anymore, as seen here: https://github.com/WeatherXM/docs/pull/84/commits/3436b4cc9daae7144e7d8bc7c5b0b7de50f6e18d

2024-05-29 23:12 UTC, NikosTsiligaridis approved these changes

2024-05-30 08:19 UTC, merged